model: gemini/gemini-2.0-flash-thinking-exp-01-21
editor-model: gemini/gemini-2.0-pro-exp-02-05
weak-model: gemini/gemini-2.0-flash
edit-format: architect
editor-edit-format: editor-whole
map-tokens: 2048
auto-commits: false
dark-mode: true

# specify common files to be edited
# file: ""
# specify read only files
# read: ["README.md", CONVENTIONS.md]